[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "climate_data_processing"
version = "0.1.0"
description = "Pipeline para ingestão e processamento de dados climáticos"
authors = [
    { name = "thais_carvalho" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "xarray",
    "esgf-pyclient",
    "pyspark",
    "pytz",
    "requests"
]

[tool.setuptools.packages.find]
where = ["."]