version: "3.8"

services:
  pyspark:
    image: bitnami/spark:latest
    container_name: pyspark
    volumes:
      - ./climate_data_processing:/app
    working_dir: /app
    command: ["spark-submit", "test_pyspark.py"]
    environment:
      - SPARK_MODE=client
    networks:
      - spark-net

networks:
  spark-net:
