version: "3.12"

services:
  raw-pipeline:
    build:
      context: ..
      dockerfile: Dockerfile

    container_name: raw_pipeline

    env_file:
      - ../.env.docker

    volumes:
    #  - ../pipeline:/app
      - ../:/app
      - ../datasets:/data
      - ../outputs:/outputs
    
    environment:
      - PYTHONPATH=/app

    # python -m pipeline/main_pipeline.py | executado como módulo
    command: >
      python -m pipeline.main_pipeline
      --stage raw
      --model ${MODEL}
      --variable ${VARIABLE}
      --exp ${EXPERIMENT}
      --freq ${FREQ}
      --year-min ${YEAR_MIN}
      --year-max ${YEAR_MAX}
    
    user: "1000:1000"
    
    restart: "no"

    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G