version: "3.12"
services:
  raw-pipeline:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: raw_pipeline
    env_file:
      - ../.env
    volumes:
      - ../datasets:/data
      - ../outputs:/outputs
    command: >
      python main_pipeline.py
      --stage raw
      --model ${MODEL}
      --variable ${VARIABLE}
      --exp ${EXPERIMENT}
      --freq ${FREQ}
      --year_min ${YEAR_MIN}
      --year_max ${YEAR_MAX}