version: "3.12"
services:
  delivery-pipeline:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: delivery_pipeline
    env_file:
      - ../.env
    volumes:
      - ../datasets:/data
      - ../outputs:/outputs
    depends_on:
      - trusted-pipeline
    command: >
      python main_pipeline.py
      --model ${MODEL}
      --variable ${VARIABLE}
      --exp ${EXPERIMENT}
      --freq ${FREQ}